FROM node:22-slim

WORKDIR /app

RUN apt-get update -y && apt-get install -y openssl

RUN npm install -g pnpm

COPY package.json pnpm-lock.yaml ./
COPY apps/backend/package.json ./apps/backend/

RUN pnpm install

COPY . .

EXPOSE 3333

CMD ["pnpm", "run", "start:backend"]
