services:
  postgres:
    image: pgvector/pgvector:pg17
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: agents
    volumes:
      - ./.docker/setup.sql:/docker-entrypoint-initdb.d/setup.sql

  # backend:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.backend
  #   ports:
  #     - 3333:3333
  #   depends_on:
  #     - postgres
